POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImluaXQxIiwiaWQiOiI2NjBmYzc2ZWRlODY5MzVlYmYwYTMzYmEiLCJpYXQiOjE3MTIzMTA1NjJ9.Ch7iSW4-bgSi9cpOPwCyMXllApJJMf1R-BNEu6yJ1SQ

{
    "title" : "new blog from init1",
    "url": "testthedelete"
}